# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ec.setGeometry(QtCore.QRect(190, 390, 75, 23))
        self.btn_ec.setObjectName("btn_ec")
        self.btn_dc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dc.setGeometry(QtCore.QRect(400, 390, 75, 23))
        self.btn_dc.setObjectName("btn_dc")
        self.txt_plaintext = QtWidgets.QListWidget(self.centralwidget)
        self.txt_plaintext.setGeometry(QtCore.QRect(140, 90, 481, 61))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 30, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_key = QtWidgets.QListWidget(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(140, 190, 471, 31))
        self.txt_key.setObjectName("txt_key")
        self.txt_ciphertext = QtWidgets.QListWidget(self.centralwidget)
        self.txt_ciphertext.setGeometry(QtCore.QRect(140, 260, 481, 61))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ec.setText(_translate("MainWindow", "Encrypt"))
        self.btn_dc.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", " Caesar Cipher"))
        self.label_2.setText(_translate("MainWindow", "plain_text  : "))
        self.label_3.setText(_translate("MainWindow", "key :"))
        self.label_4.setText(_translate("MainWindow", "cipher_text  : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
